version: '3.8'
services:
  mek-db:
    image: postgres:latest
    container_name: cve-postgres-container
    environment:
      POSTGRES_USER: cveuser
      POSTGRES_PASSWORD: cveuser-password
      POSTGRES_DB: cve
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: local-cve-db
